- name: deploy the webapp
  hosts: webservers
  tasks:
          - name: install Docker engine
            become: true
            apt: name=docker-ce update_cache=yes

          - name: install pip
            become: true
            apt: name=python-pip 

          - name: usermod ubuntu 
            become: true
            shell: usermod -aG docker ubuntu

          - name: Install Docker Module for Python
            pip:
               name: docker
          - name: install the latest version of compose
            become: true
            shell: curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose && chmod +x /usr/bin/docker-compose

          - name: copy app folder
            copy:
                    src: ./myapp
                    dest: /home/ubuntu/
          - name: Build docker frontend image
            docker_image:
                    name: mywebapp
                    path: ./myapp/flask

          - name: Build mysqldb image
            docker_image:
                    name: mysqldb
                    path: ./myapp/mysql
          #- name: Create the web container
          #docker_container:
          #          image: mywebapp
          #          state: started
          #          name: mywebapp
          #          published_ports: 80:80
          #- name: Create the DB container
          #  docker_container:
          #         image: mysqldb
          #          state: started
          #          name: mysqldb
          #          published_ports: 3306:3306
          - name: Run the app
            shell: docker-compose -f myapp/docker-compose.yml up -d




                  


        
