- name: deploy the webapp
  hosts: webservers
  tasks:
          - name: apt-get update
            become: true
            apt:
                    upgrade: yes
                    update_cache: yes
          - name: install Docker engine
            become: true
            #shell: curl -fsSL https://get.docker.com | sh
            apt: name=docker.io

          - name: install pip
            become: true
            apt: name=python3-pip 

          - name: usermod ubuntu 
            become: true
            shell: usermod -aG docker ubuntu

          - name: Install Docker Module for Python
            pip:
               name: docker
          - name: install the latest version of compose
            become: true
            shell: curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose && chmod +x /usr/bin/docker-compose

          - name: copy app folder
            copy:
                    src: ./myapp
                    dest: /home/ubuntu/

          - name: Build docker frontend image
            become: true
            #docker_image:
            #        name: mywebapp
            #        path: ./myapp/flask

            shell: docker build -t mywebapp ./myapp/flask

          - name: Build mysqldb image
            become: true
            #docker_image:
            #        name: mysqldb
            #        path: ./myapp/mysql
            shell: docker build -t mysqldb ./myapp/mysql
          
          - name: Run the app
            shell: docker-compose -f myapp/docker-compose.yml up -d
            retries: 3
            delay: 3
            register: result
            until: result.rc == 0
